/*사용자 테이블 */
CREATE TABLE TB_USER (
	ID VARCHAR2(100) PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	PASSWORD VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(100),
	PHONE_NO VARCHAR2(100),
	IS_ADMIN VARCHAR2(5),
	VIEWCOUNT NUMBER,
	REGDATE DATE 	
);

/* 파일 업로드테이블 */
CREATE TABLE TB_FILE(
	NUM NUMBER,
	ID VARCHAR2(100),
	ORGFILENAME VARCHAR2(500),
	SAVEFILENAME VARCHAR2(500),
	FILESIZE NUMBER
);

CREATE SEQUENCE TB_FILE_SEQ;


/* 경력(이력) 테이블 */
CREATE TABLE TB_EXPS (
	NUM NUMBER PRIMARY KEY,
	ID VARCHAR2(100) NOT NULL,
	POSITION VARCHAR2(100),
	PLACE VARCHAR2(100),
	EX_EXP CLOB,
	START_DATE DATE,
	END_DATE DATE
);

CREATE SEQUENCE EXPS_SEQ;


/* 교육사항 테이블 */
CREATE TABLE TB_EDU (
	NUM NUMBER PRIMARY KEY,
	ID VARCHAR2(100) NOT NULL,
	PLACE VARCHAR2(100),
	MAJOR VARCHAR2(100),
	EDU_EXP CLOB,
	START_DATE DATE,
	END_DATE DATE
);

CREATE SEQUENCE EDU_SEQ;


/* 보유기술 테이블 */
CREATE TABLE TB_SKILLS (
	NUM NUMBER PRIMARY KEY,
	ID VARCHAR2(100) NOT NULL,
	SKILL_NM VARCHAR2(50),
	SKILL_EXP CLOB
);

CREATE SEQUENCE SKILLS_SEQ;

/* 관심사 테이블 */
CREATE TABLE TB_INTS (
	NUM NUMBER PRIMARY KEY,
	ID VARCHAR2(100) NOT NULL,
	INTS_NM VARCHAR2(50),
	INTS_EXP CLOB
);

CREATE SEQUENCE INTS_SEQ;

/* 수상 자격증 테이블 */
CREATE TABLE TB_AC (
	NUM NUMBER PRIMARY KEY,
	ID VARCHAR2(100) NOT NULL,
	AC_NM VARCHAR2(50),
	AC_EXP CLOB,
	AC_DATE DATE
);

CREATE SEQUENCE AC_SEQ;

/* 채용공고 게시판 테이블 */
CREATE TABLE TB_BOARD_CAFE (
	NUM NUMBER,
	WRITER VARCHAR2(20),
	TITLE VARCHAR2(200),
	CONTENT CLOB,
	VIEWCOUNT NUMBER,
	REGDATE DATE
);

CREATE SEQUENCE TB_BOARD_CAFE_SEQ;

